### ISSUE TITLE
错误报告：unsupported platform: android

### ISSUE THREAD

**Issue by JIANever404** [easydu2002/chat_gpt_oicq#20]
**检查清单**
- [1 ] 我使用的是最新版本的dev分支。
- [1 ] 我已经查询过现有的issue。

**错误复现步骤**
![image](https://user-images.githubusercontent.com/49186407/209542050-39cbcf83-f5b1-450c-ac88-7b5202eecf6b.png)
![image](https://user-images.githubusercontent.com/49186407/209542074-0c9aa9ff-f1de-48c4-a0ad-6337f623a418.png)
![image](https://user-images.githubusercontent.com/49186407/209542091-2aacb867-c61a-4491-b175-1694be2debed.png)
![image](https://user-images.githubusercontent.com/49186407/209542180-92e7c857-f520-4b06-9ab6-fed7bc37bb41.png)

**Comment by JIANever404** [comment]
手机是小米6 miui 12 20.6.18

**Comment by JIANever404** [comment]
尝试过删除version-local，无用

**Comment by easydu2002** [comment]
#16 
目前在termux上面确实有这个问题
可以先这么解决 `export PUPPETEER_SKIP_DOWNLOAD=true && ./start.sh`

**Comment by JIANever404** [comment]
> #16 目前在termux上面确实有这个问题 可以先这么解决 `export PUPPETEER_SKIP_DOWNLOAD=true && ./start.sh`

问题依然存在：
~/chat_gpt_oicq $ export PUPPETEER_SKP_DOWNLOAD=true && ./start.sh                    启动中，请稍等
如果使用该脚本出现异常情况，请先尝试删除目录下的 version-local 文件, 或提交问题至 https://github.com/easydu2002/chat_gpt_oicq/issues
正在更新依赖，请稍等...
[##################] | reify:typescript: timing reifyNode:node_modules/rxjs Completed
> puppeteer@19.4.1 postinstall
> node install.js

/data/data/com.termux/files/home/chat_gpt_oicq/node_modules/puppeteer-core/lib/cjs/puppeteer/util/assert.js:28
        throw new Error(message);
              ^

Error: Unsupported platform: android
    at assert (/data/data/com.termux/files/home/chat_gpt_oicq/node_modules/puppeteer-core/lib/cjs/puppeteer/util/assert.js:28:15)
    at new BrowserFetcher (/data/data/com.termux/files/home/chat_gpt_oicq/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserFetcher.js:215:44)
    at downloadBrowser (/data/data/com.termux/files/home/chat_gpt_oicq/node_modules/puppeteer/lib/cjs/puppeteer/node/install.js:49:28)
    at Object.<anonymous> (/data/data/com.termux/files/home/chat_gpt_oicq/node_modules/puppeteer/install.js:40:1)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47

Node.js v18.12.1
npm ERR! code 1
npm ERR! path /data/data/com.termux/files/home/chat_gpt_oicq/node_modules/puppeteer
npm ERR! command failed
npm ERR! command sh -c -- node install.js

npm ERR! A complete log of this run can be found in:
npm ERR!     /data/data/com.termux/files/home/.npm/_logs/2022-12-27T01_40_01_816Z-debug-0.log
~/chat_gpt_oicq $
~/chat_gpt_oicq $
~/chat_gpt_oicq $

**Comment by JIANever404** [comment]
> #16 目前在termux上面确实有这个问题 可以先这么解决 `export PUPPETEER_SKIP_DOWNLOAD=true && ./start.sh`

有效 谢谢
